---
- name: Actualizar ssoo
  apt:
    upgrade: yes
    update_cache: yes
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"

- name: Habilitar firewall y permitir ssh
  ufw:
    state: enabled
    rule: allow
    port: 22
    direction: in
  
- name: Añadir hosts a /etc/hosts
  template:
    src: "templates/hosts.j2"
    dest: "/etc/hosts"
    mode: 644
    owner: root
    group: root