---

- name: Allow bind non local IP (VIP)
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present
  become: yes

- name: Permitir rango de puertos para haproxy y keepalived
  ufw:
    state: enabled
    rule: allow
    port: '{{ item }}'
    direction: in
    proto: tcp
  with_items:
  - '6443' #API
  - '80'
  - '443'

- name: Instalar keepalived
  apt:
    name: '{{ packages }}'
    update_cache: yes
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  vars:
    packages:
      - 'keepalived={{ keepalived_version }}'

- name: Copiar configuración keepalived
  template:
    src: templates/keepalived.j2
    dest: /etc/keepalived/keepalived.conf

- name: Habilitar servicio keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started

- name: Marcar paquetes para que no se actualicen
  dpkg_selections:
    name: keepalived
    selection: hold